<?php

return array(
	'color' => array(
		'red' => 'Red',
		'yellow' => 'Yellow',
		'blue' => 'Blue',
		'violet' => 'Violet',
		'orange' => 'Orange',
		'green' => 'Green',
	),
    'font' => array(
        'heading' => array(
            'font-name' => 'Exo',
            'font-family' => 'Exo',
            'font-weight' => '300,400,600,700',
            'font-selector' => '.primary-define h1,
								.primary-define h2,
								.primary-define h3,
								.primary-define h4,
								.primary-define h5,
								.primary-define h6,
								.primary-define .button,
								.primary-define .htabs a,
								.primary-define .box-heading,
								.primary-define .breadcrumb a,
								.primary-define .mainmenu li a,
								.primary-define .treemenu li a,
								.primary-define .box-product .name a,
								.primary-define .box-product .cart a,
								.primary-define .box-product .price,
								.primary-define .box-product .price-label,
								.primary-define .box-product .wishlist a,
								.primary-define .box-product .compare a,
								.primary-define .product-info .price,
								.primary-define .product-info .review a,
								.primary-define .product-info .cart > div > a,
								.primary-define .kuler-accordion .item-title,
								.primary-define #menu #btn-mobile-toggle',
            'css-name' => 'Exo',
        ),
        'body' => array(
            'font-name' => 'Open Sans',
            'font-family' => 'Open Sans',
            'font-weight' => '400,600,700',
            'font-selector' => 'body,
								.primary-define input,
								.primary-define select,
								.primary-define button,
								.primary-define textarea,
								.primary-define .product-info .reward,
								.primary-define .product-info .discount,
								.primary-define .product-info .price-tax,
								.primary-define .kuler-tabs .kuler-tabs-content',
            'css-name' => 'Open+Sans',
        ),
    ),
    
);

?>